version: '3.9'

services:
  cassandra:
    image: docker.io/bitnami/cassandra:latest
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - './data/cassandra:/bitnami'
    environment:
      - CASSANDRA_HOST=127.0.0.1
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra

