server:
  servlet:
    context-path: /bookstore/v1
  port: 8089

spring:
  cassandra:
    port: 9042
    contact-points: 127.0.0.1
    keyspace_name: book_store
    schema-action: CREATE_IF_NOT_EXISTS
    #uername: cassandra
    # password: cassandra