server:
  servlet:
    context-path: /bookstore/v1
  port: 9999

spring:
  cassandra:
    port: 9042
    contact-points: 127.0.0.1
    keyspace_name: keyspace_bookstore
    schema-action: CREATE_IF_NOT_EXISTS
    password: cassandra
    #username: cassandra